-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.active_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id text NOT NULL,
  chatbot_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  last_activity_at timestamp with time zone DEFAULT now(),
  CONSTRAINT active_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT active_conversations_conversation_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT active_conversations_chatbot_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.ai_usage_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  usage_type text NOT NULL CHECK (usage_type = ANY (ARRAY['chunk_enrichment'::text, 'chat_response'::text, 'summarization'::text, 'embedding_generation'::text, 'custom'::text])),
  chunk_id uuid,
  conversation_id uuid,
  knowledge_entry_id uuid,
  chatbot_id uuid,
  user_id uuid,
  model_name text NOT NULL,
  input_text text NOT NULL,
  output_text text,
  input_tokens integer CHECK (input_tokens >= 0),
  output_tokens integer CHECK (output_tokens >= 0),
  total_tokens integer CHECK (total_tokens >= 0),
  latency_ms integer NOT NULL CHECK (latency_ms >= 0),
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'timeout'::text, 'rate_limited'::text])),
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_logs_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.knowledge_chunks(id),
  CONSTRAINT ai_usage_logs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT ai_usage_logs_knowledge_entry_id_fkey FOREIGN KEY (knowledge_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT ai_usage_logs_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT ai_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  key_hash text NOT NULL UNIQUE,
  key_prefix text NOT NULL,
  scopes ARRAY DEFAULT ARRAY[]::text[],
  last_used_at timestamp with time zone,
  usage_count integer DEFAULT 0,
  rate_limit_per_minute integer DEFAULT 60,
  rate_limit_per_hour integer DEFAULT 3600,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.brands (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  logo_url text,
  theme_color text DEFAULT '#3B82F6'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT brands_pkey PRIMARY KEY (id),
  CONSTRAINT brands_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  session_id text NOT NULL,
  user_id uuid,
  client_ip inet,
  user_agent text,
  message_direction text NOT NULL CHECK (message_direction = ANY (ARRAY['incoming'::text, 'outgoing'::text])),
  message_type text NOT NULL DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'file'::text, 'system'::text, 'error'::text, 'quick_reply'::text])),
  content text NOT NULL,
  formatted_content jsonb,
  ai_model text,
  prompt_tokens integer CHECK (prompt_tokens >= 0),
  completion_tokens integer CHECK (completion_tokens >= 0),
  total_tokens integer CHECK (total_tokens >= 0),
  processing_time_ms integer CHECK (processing_time_ms >= 0),
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'timeout'::text, 'rate_limited'::text, 'pending'::text])),
  error_message text,
  error_code text,
  source_chunks jsonb DEFAULT '[]'::jsonb,
  source_entry_id uuid,
  sentiment text CHECK (sentiment = ANY (ARRAY['positive'::text, 'negative'::text, 'neutral'::text])),
  was_helpful boolean,
  user_feedback text,
  feedback_rating integer CHECK (feedback_rating >= 1 AND feedback_rating <= 5),
  parent_message_id uuid,
  thread_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  extracted_entities jsonb DEFAULT '{}'::jsonb,
  conversation_summary text,
  message_intent text,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT chat_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_messages_source_entry_id_fkey FOREIGN KEY (source_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT chat_messages_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.chat_prompts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  prompt_text text NOT NULL,
  temperature double precision DEFAULT 0.7 CHECK (temperature >= 0.0::double precision AND temperature <= 1.0::double precision),
  context_size integer DEFAULT 2000,
  top_p double precision DEFAULT 0.9 CHECK (top_p >= 0.0::double precision AND top_p <= 1.0::double precision),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT chat_prompts_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.chatbot_store_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbot_id uuid NOT NULL,
  store_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chatbot_store_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_store_integrations_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT chatbot_store_integrations_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.chatbots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  brand_id uuid,
  name text NOT NULL,
  avatar_url text,
  primary_color text DEFAULT '#3B82F6'::text,
  secondary_color text DEFAULT '#EF4444'::text,
  animation_style text DEFAULT 'fade'::text,
  script_token text NOT NULL DEFAULT (uuid_generate_v4())::text UNIQUE,
  language text DEFAULT 'tr'::text CHECK (language = ANY (ARRAY['tr'::text, 'en'::text, 'de'::text, 'fr'::text, 'es'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'inactive'::text, 'published'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  chatbox_title character varying DEFAULT 'Zzen Chatbox'::character varying,
  initial_message text DEFAULT 'Hello! It''s Orbina here!'::text,
  placeholder_text character varying DEFAULT 'Mesajınızı yazın...'::character varying,
  ai_message_color character varying DEFAULT '#E5E7EB'::character varying,
  user_message_color character varying DEFAULT '#7B4DFA'::character varying,
  ai_text_color character varying DEFAULT '#1F2937'::character varying,
  user_text_color character varying DEFAULT '#FFFFFF'::character varying,
  button_primary_color character varying DEFAULT '#7B4DFA'::character varying,
  button_border_color character varying DEFAULT '#B794F6'::character varying,
  button_icon_color character varying DEFAULT '#FFFFFF'::character varying,
  store_id uuid,
  user_id uuid,
  CONSTRAINT chatbots_pkey PRIMARY KEY (id),
  CONSTRAINT chatbots_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id),
  CONSTRAINT chatbots_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT chatbots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chatbox_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbox_id uuid NOT NULL,
  product_id uuid NOT NULL UNIQUE,
  show_on_product_page boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  show_on_store_homepage boolean DEFAULT true,
  CONSTRAINT chatbox_products_pkey PRIMARY KEY (id),
  CONSTRAINT fk_chatbox_products_chatbox FOREIGN KEY (chatbox_id) REFERENCES public.chatbots(id),
  CONSTRAINT fk_chatbox_products_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.chatbox_stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbox_id uuid NOT NULL,
  store_id uuid NOT NULL,
  show_on_homepage boolean DEFAULT true,
  show_on_products boolean DEFAULT true,
  position character varying DEFAULT 'bottom-right'::character varying CHECK ("position"::text = ANY (ARRAY['bottom-right'::character varying, 'bottom-left'::character varying, 'top-right'::character varying, 'top-left'::character varying]::text[])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chatbox_stores_pkey PRIMARY KEY (id),
  CONSTRAINT fk_chatbox_stores_chatbox FOREIGN KEY (chatbox_id) REFERENCES public.chatbots(id),
  CONSTRAINT fk_chatbox_stores_store FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.chunk_enrichment_jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  knowledge_entry_id uuid NOT NULL,
  chatbot_id uuid,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  total_chunks integer DEFAULT 0 CHECK (total_chunks >= 0),
  processed_chunks integer DEFAULT 0 CHECK (processed_chunks >= 0),
  failed_chunks integer DEFAULT 0 CHECK (failed_chunks >= 0),
  prompt_template text,
  ai_model text DEFAULT 'meta-llama/llama-3.1-8b-instruct:free'::text,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chunk_enrichment_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT chunk_enrichment_jobs_knowledge_entry_fkey FOREIGN KEY (knowledge_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT chunk_enrichment_jobs_chatbot_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT chunk_enrichment_jobs_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  session_id text NOT NULL,
  user_input text NOT NULL,
  bot_response text NOT NULL,
  source_entry_id uuid,
  latency_ms integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  sentiment character varying CHECK (sentiment::text = ANY (ARRAY['positive'::character varying, 'negative'::character varying, 'neutral'::character varying]::text[])),
  was_helpful boolean,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'closed'::text, 'archived'::text])),
  user_session_id uuid,
  message_count integer DEFAULT 0,
  last_message_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  conversation_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT conversations_source_entry_id_fkey FOREIGN KEY (source_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT conversations_user_session_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id)
);
CREATE TABLE public.email_verification_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE,
  email text NOT NULL,
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  client_ip inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT email_verification_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.knowledge_base_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['manual'::text, 'pdf'::text, 'url'::text, 'txt'::text, 'text'::text, 'website'::text])),
  source_url text,
  content text,
  embedding_id text,
  token_count integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'ready'::text, 'processed'::text, 'failed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  source_name character varying,
  storage_path text,
  file_size bigint,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  CONSTRAINT knowledge_base_entries_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_base_entries_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.knowledge_chunks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  knowledge_entry_id uuid NOT NULL,
  chatbot_id uuid,
  chunk_index integer NOT NULL CHECK (chunk_index >= 0),
  content text NOT NULL,
  token_count integer DEFAULT 0 CHECK (token_count >= 0),
  embedding USER-DEFINED,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_chunks_knowledge_entry_fkey FOREIGN KEY (knowledge_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT knowledge_chunks_chatbot_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.password_reset_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE,
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  client_ip inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '01:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.product_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  image_url text NOT NULL,
  alt_text text,
  display_order integer NOT NULL DEFAULT 0,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  thumbnail_url text,
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  user_id uuid,
  reviewer_name text NOT NULL,
  reviewer_email text,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  verified_purchase boolean DEFAULT false,
  helpful_count integer DEFAULT 0 CHECK (helpful_count >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  short_description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  compare_at_price numeric,
  cost_price numeric CHECK (cost_price IS NULL OR cost_price >= 0::numeric),
  category text NOT NULL,
  subcategory text,
  sku text,
  barcode text,
  stock_quantity integer DEFAULT 0 CHECK (stock_quantity >= 0),
  track_inventory boolean DEFAULT true,
  allow_backorder boolean DEFAULT false,
  weight numeric CHECK (weight IS NULL OR weight >= 0::numeric),
  dimensions jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  featured boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  meta_title text,
  meta_description text,
  average_rating numeric DEFAULT 0.00 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  review_count integer DEFAULT 0 CHECK (review_count >= 0),
  view_count integer DEFAULT 0 CHECK (view_count >= 0),
  sales_count integer DEFAULT 0 CHECK (sales_count >= 0),
  seo_data jsonb DEFAULT '{}'::jsonb,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'inactive'::text])),
  platform text CHECK (platform = ANY (ARRAY['web'::text, 'mobile'::text, 'both'::text])),
  primary_color text DEFAULT '#000000'::text,
  secondary_color text DEFAULT '#FFFFFF'::text,
  text_color text DEFAULT '#000000'::text,
  description text,
  meta_title text,
  meta_description text,
  custom_domain text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT stores_pkey PRIMARY KEY (id),
  CONSTRAINT stores_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.uploads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  storage_url text NOT NULL,
  processed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT uploads_pkey PRIMARY KEY (id),
  CONSTRAINT uploads_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.user_audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  event_type text NOT NULL,
  event_description text,
  event_data jsonb DEFAULT '{}'::jsonb,
  client_ip inet,
  user_agent text,
  request_method text,
  request_path text,
  risk_level text DEFAULT 'low'::text CHECK (risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  is_suspicious boolean DEFAULT false,
  country_code text,
  city text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT user_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id text NOT NULL UNIQUE,
  user_id uuid,
  user_profile jsonb DEFAULT '{}'::jsonb,
  client_ip inet,
  user_agent text,
  first_seen_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  full_name text,
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'admin'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  username text UNIQUE CHECK (username ~ '^[a-zA-Z0-9_-]{3,30}$'::text),
  avatar_url text,
  avatar_type text DEFAULT 'gravatar'::text CHECK (avatar_type = ANY (ARRAY['upload'::text, 'gravatar'::text, 'initials'::text])),
  avatar_updated_at timestamp with time zone,
  password_hash text,
  email_confirmed_at timestamp with time zone,
  raw_app_meta_data jsonb DEFAULT '{}'::jsonb,
  raw_user_meta_data jsonb DEFAULT '{}'::jsonb,
  aud text DEFAULT 'authenticated'::text,
  confirmation_token text,
  recovery_token text,
  phone text,
  phone_confirmed_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.active_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id text NOT NULL,
  chatbot_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  last_activity_at timestamp with time zone DEFAULT now(),
  CONSTRAINT active_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT active_conversations_conversation_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT active_conversations_chatbot_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.ai_usage_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  usage_type text NOT NULL CHECK (usage_type = ANY (ARRAY['chunk_enrichment'::text, 'chat_response'::text, 'summarization'::text, 'embedding_generation'::text, 'custom'::text])),
  chunk_id uuid,
  conversation_id uuid,
  knowledge_entry_id uuid,
  chatbot_id uuid,
  user_id uuid,
  model_name text NOT NULL,
  input_text text NOT NULL,
  output_text text,
  input_tokens integer CHECK (input_tokens >= 0),
  output_tokens integer CHECK (output_tokens >= 0),
  total_tokens integer CHECK (total_tokens >= 0),
  latency_ms integer NOT NULL CHECK (latency_ms >= 0),
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'timeout'::text, 'rate_limited'::text])),
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_logs_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.knowledge_chunks(id),
  CONSTRAINT ai_usage_logs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT ai_usage_logs_knowledge_entry_id_fkey FOREIGN KEY (knowledge_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT ai_usage_logs_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT ai_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  key_hash text NOT NULL UNIQUE,
  key_prefix text NOT NULL,
  scopes ARRAY DEFAULT ARRAY[]::text[],
  last_used_at timestamp with time zone,
  usage_count integer DEFAULT 0,
  rate_limit_per_minute integer DEFAULT 60,
  rate_limit_per_hour integer DEFAULT 3600,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.brands (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  logo_url text,
  theme_color text DEFAULT '#3B82F6'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT brands_pkey PRIMARY KEY (id),
  CONSTRAINT brands_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  session_id text NOT NULL,
  user_id uuid,
  client_ip inet,
  user_agent text,
  message_direction text NOT NULL CHECK (message_direction = ANY (ARRAY['incoming'::text, 'outgoing'::text])),
  message_type text NOT NULL DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'file'::text, 'system'::text, 'error'::text, 'quick_reply'::text])),
  content text NOT NULL,
  formatted_content jsonb,
  ai_model text,
  prompt_tokens integer CHECK (prompt_tokens >= 0),
  completion_tokens integer CHECK (completion_tokens >= 0),
  total_tokens integer CHECK (total_tokens >= 0),
  processing_time_ms integer CHECK (processing_time_ms >= 0),
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'timeout'::text, 'rate_limited'::text, 'pending'::text])),
  error_message text,
  error_code text,
  source_chunks jsonb DEFAULT '[]'::jsonb,
  source_entry_id uuid,
  sentiment text CHECK (sentiment = ANY (ARRAY['positive'::text, 'negative'::text, 'neutral'::text])),
  was_helpful boolean,
  user_feedback text,
  feedback_rating integer CHECK (feedback_rating >= 1 AND feedback_rating <= 5),
  parent_message_id uuid,
  thread_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  extracted_entities jsonb DEFAULT '{}'::jsonb,
  conversation_summary text,
  message_intent text,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT chat_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_messages_source_entry_id_fkey FOREIGN KEY (source_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT chat_messages_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.chat_prompts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  prompt_text text NOT NULL,
  temperature double precision DEFAULT 0.7 CHECK (temperature >= 0.0::double precision AND temperature <= 1.0::double precision),
  context_size integer DEFAULT 2000,
  top_p double precision DEFAULT 0.9 CHECK (top_p >= 0.0::double precision AND top_p <= 1.0::double precision),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT chat_prompts_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.chatbot_store_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbot_id uuid NOT NULL,
  store_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chatbot_store_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_store_integrations_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT chatbot_store_integrations_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.chatbots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  brand_id uuid,
  name text NOT NULL,
  avatar_url text,
  primary_color text DEFAULT '#3B82F6'::text,
  secondary_color text DEFAULT '#EF4444'::text,
  animation_style text DEFAULT 'fade'::text,
  script_token text NOT NULL DEFAULT (uuid_generate_v4())::text UNIQUE,
  language text DEFAULT 'tr'::text CHECK (language = ANY (ARRAY['tr'::text, 'en'::text, 'de'::text, 'fr'::text, 'es'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'inactive'::text, 'published'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  chatbox_title character varying DEFAULT 'Zzen Chatbox'::character varying,
  initial_message text DEFAULT 'Hello! It''s Orbina here!'::text,
  placeholder_text character varying DEFAULT 'Mesajınızı yazın...'::character varying,
  ai_message_color character varying DEFAULT '#E5E7EB'::character varying,
  user_message_color character varying DEFAULT '#7B4DFA'::character varying,
  ai_text_color character varying DEFAULT '#1F2937'::character varying,
  user_text_color character varying DEFAULT '#FFFFFF'::character varying,
  button_primary_color character varying DEFAULT '#7B4DFA'::character varying,
  button_border_color character varying DEFAULT '#B794F6'::character varying,
  button_icon_color character varying DEFAULT '#FFFFFF'::character varying,
  store_id uuid,
  user_id uuid,
  CONSTRAINT chatbots_pkey PRIMARY KEY (id),
  CONSTRAINT chatbots_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id),
  CONSTRAINT chatbots_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT chatbots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chatbox_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbox_id uuid NOT NULL,
  product_id uuid NOT NULL UNIQUE,
  show_on_product_page boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  show_on_store_homepage boolean DEFAULT true,
  CONSTRAINT chatbox_products_pkey PRIMARY KEY (id),
  CONSTRAINT fk_chatbox_products_chatbox FOREIGN KEY (chatbox_id) REFERENCES public.chatbots(id),
  CONSTRAINT fk_chatbox_products_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.chatbox_stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbox_id uuid NOT NULL,
  store_id uuid NOT NULL,
  show_on_homepage boolean DEFAULT true,
  show_on_products boolean DEFAULT true,
  position character varying DEFAULT 'bottom-right'::character varying CHECK ("position"::text = ANY (ARRAY['bottom-right'::character varying, 'bottom-left'::character varying, 'top-right'::character varying, 'top-left'::character varying]::text[])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chatbox_stores_pkey PRIMARY KEY (id),
  CONSTRAINT fk_chatbox_stores_chatbox FOREIGN KEY (chatbox_id) REFERENCES public.chatbots(id),
  CONSTRAINT fk_chatbox_stores_store FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.chunk_enrichment_jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  knowledge_entry_id uuid NOT NULL,
  chatbot_id uuid,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  total_chunks integer DEFAULT 0 CHECK (total_chunks >= 0),
  processed_chunks integer DEFAULT 0 CHECK (processed_chunks >= 0),
  failed_chunks integer DEFAULT 0 CHECK (failed_chunks >= 0),
  prompt_template text,
  ai_model text DEFAULT 'meta-llama/llama-3.1-8b-instruct:free'::text,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chunk_enrichment_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT chunk_enrichment_jobs_knowledge_entry_fkey FOREIGN KEY (knowledge_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT chunk_enrichment_jobs_chatbot_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT chunk_enrichment_jobs_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  session_id text NOT NULL,
  user_input text NOT NULL,
  bot_response text NOT NULL,
  source_entry_id uuid,
  latency_ms integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  sentiment character varying CHECK (sentiment::text = ANY (ARRAY['positive'::character varying, 'negative'::character varying, 'neutral'::character varying]::text[])),
  was_helpful boolean,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'closed'::text, 'archived'::text])),
  user_session_id uuid,
  message_count integer DEFAULT 0,
  last_message_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  conversation_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT conversations_source_entry_id_fkey FOREIGN KEY (source_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT conversations_user_session_fkey FOREIGN KEY (user_session_id) REFERENCES public.user_sessions(id)
);
CREATE TABLE public.email_verification_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE,
  email text NOT NULL,
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  client_ip inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT email_verification_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.knowledge_base_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['manual'::text, 'pdf'::text, 'url'::text, 'txt'::text, 'text'::text, 'website'::text])),
  source_url text,
  content text,
  embedding_id text,
  token_count integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'ready'::text, 'processed'::text, 'failed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  source_name character varying,
  storage_path text,
  file_size bigint,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  CONSTRAINT knowledge_base_entries_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_base_entries_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.knowledge_chunks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  knowledge_entry_id uuid NOT NULL,
  chatbot_id uuid,
  chunk_index integer NOT NULL CHECK (chunk_index >= 0),
  content text NOT NULL,
  token_count integer DEFAULT 0 CHECK (token_count >= 0),
  embedding USER-DEFINED,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_chunks_knowledge_entry_fkey FOREIGN KEY (knowledge_entry_id) REFERENCES public.knowledge_base_entries(id),
  CONSTRAINT knowledge_chunks_chatbot_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.password_reset_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL UNIQUE,
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  client_ip inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '01:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.product_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  image_url text NOT NULL,
  alt_text text,
  display_order integer NOT NULL DEFAULT 0,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  thumbnail_url text,
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  user_id uuid,
  reviewer_name text NOT NULL,
  reviewer_email text,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  verified_purchase boolean DEFAULT false,
  helpful_count integer DEFAULT 0 CHECK (helpful_count >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  short_description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  compare_at_price numeric,
  cost_price numeric CHECK (cost_price IS NULL OR cost_price >= 0::numeric),
  category text NOT NULL,
  subcategory text,
  sku text,
  barcode text,
  stock_quantity integer DEFAULT 0 CHECK (stock_quantity >= 0),
  track_inventory boolean DEFAULT true,
  allow_backorder boolean DEFAULT false,
  weight numeric CHECK (weight IS NULL OR weight >= 0::numeric),
  dimensions jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  featured boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  meta_title text,
  meta_description text,
  average_rating numeric DEFAULT 0.00 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  review_count integer DEFAULT 0 CHECK (review_count >= 0),
  view_count integer DEFAULT 0 CHECK (view_count >= 0),
  sales_count integer DEFAULT 0 CHECK (sales_count >= 0),
  seo_data jsonb DEFAULT '{}'::jsonb,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'inactive'::text])),
  platform text CHECK (platform = ANY (ARRAY['web'::text, 'mobile'::text, 'both'::text])),
  primary_color text DEFAULT '#000000'::text,
  secondary_color text DEFAULT '#FFFFFF'::text,
  text_color text DEFAULT '#000000'::text,
  description text,
  meta_title text,
  meta_description text,
  custom_domain text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT stores_pkey PRIMARY KEY (id),
  CONSTRAINT stores_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id)
);
CREATE TABLE public.uploads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chatbot_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  storage_url text NOT NULL,
  processed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT uploads_pkey PRIMARY KEY (id),
  CONSTRAINT uploads_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id)
);
CREATE TABLE public.user_audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  event_type text NOT NULL,
  event_description text,
  event_data jsonb DEFAULT '{}'::jsonb,
  client_ip inet,
  user_agent text,
  request_method text,
  request_path text,
  risk_level text DEFAULT 'low'::text CHECK (risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  is_suspicious boolean DEFAULT false,
  country_code text,
  city text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT user_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id text NOT NULL UNIQUE,
  user_id uuid,
  user_profile jsonb DEFAULT '{}'::jsonb,
  client_ip inet,
  user_agent text,
  first_seen_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  full_name text,
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'admin'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  username text UNIQUE CHECK (username ~ '^[a-zA-Z0-9_-]{3,30}$'::text),
  avatar_url text,
  avatar_type text DEFAULT 'gravatar'::text CHECK (avatar_type = ANY (ARRAY['upload'::text, 'gravatar'::text, 'initials'::text])),
  avatar_updated_at timestamp with time zone,
  password_hash text,
  email_confirmed_at timestamp with time zone,
  raw_app_meta_data jsonb DEFAULT '{}'::jsonb,
  raw_user_meta_data jsonb DEFAULT '{}'::jsonb,
  aud text DEFAULT 'authenticated'::text,
  confirmation_token text,
  recovery_token text,
  phone text,
  phone_confirmed_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);